### PR TITLE
add.py modified to have one core app.

### PR DESCRIPTION
**Pull request by lvalics**
I modified the app.py file because I saw that it was no longer used (probably it was an older code).
Now, having three versions—low, normal, and Mac—will create chaos in the code for maintenance.
My suggestion is to review the app.py and see if this approach is okay.

At the moment, for some reason, it generates images with noise; I probably made a mistake, but someone who knows the code could surely find the error (if I don’t have time to find it myself).

It starts with a command line, for example:

python app.py --mode normal --debug

It’s a draft, do not make it public until the bug is fixed and tested.

### CODE REVIEW

**Comment by lvalics** [comment]
Now it is working, if you approve, I will add latest modification you added ... Also one part is not clear to me.  Check here, does not get global, so I cannot separate logic. print ("Low VRAM 2")

**Comment by lvalics** [comment]
If you want to drop main one, and keep only the low vram, just reject this modification, it is not needed then.

**Comment by Z-YuPeng** [comment]
> I modified the app.py file because I saw that it was no longer used (probably it was an older code).
> Now, having three versions—low, normal, and Mac—will create chaos in the code for maintenance.
> My suggestion is to review the app.py and see if this approach is okay.

I can‘t agree more,   current code is chaos. It appears that the original version can be deleted, with the low VRAM version and the Apple version being retained. Also app.py maybe too long, Perhaps some of the code needs to be moved into the utils. I am currently developing a Comfui plugin and will come back to organize the code later.

**Comment by lvalics** [comment]
OK, so for now drop this one, I will do the merge for the Mac and LowVRAm one into app.py today. Then later we can start to arrange the code and add more features. I like the project!

**Pull request closed without merging**
